language: c++

git:
  quiet: true
  submodules: true

addons:
  apt:
    update: true
    packages:
      - libomp-dev
      - nvptx-tools
      - gcc-offload-nvptx

script:
  - make clean test
  - make openmp clean test
  - make gpu clean test
