language: c++

git:
  quiet: true
  submodules: true

addons:
  apt:
    update: true
    packages:
      - g++-10
      - libomp-dev
      - mpic++

script:
  - make clean test
  - make CCFLAGS=-DCPU_LIMIT=0 openmp clean test
  - make mpi clean test
  - make CCFLAGS=-DCPU_LIMIT=0 mpi openmp clean test
