language: c++

git:
  quiet: true
  submodules: true

addons:
  apt:
    update: true
    packages:
      - libomp-dev

script:
  - make clean test
  - make --environment-overrides LDLIBS=-fopenmp clean test
