language: c++

git:
  quiet: true
  submodules: true

addons:
  apt:
    update: true
    packages:
      - libomp-dev
      - mpic++

script:
  - make clean test
  - make openmp clean test
  - make mpi clean test
  - make mpi openmp clean test
